apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: doc-empty-template
  title: Empty Template
  description: First Step - Learn How To Create Empty Template
  tags:
    - empty
    - documentation
    - discovery

spec:
  owner: thd@edocumentation.com
  type: service

steps:
  - id: register
      name: Register
      action: debug:log
      input:
        message: "Registered"
